### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by Chum4k3r** [shomykohai/shomykohai.github.io#1]
The shomy.is-a.dev link seems to be broken. It just redirects to the is-a.dev home page

The quest system documentations are unaccessible

Please check that out

**Comment by shomykohai** [comment]
Hello,
unfortunately this issue comes from the is-a.dev domain (see README here https://github.com/is-a-dev/register).

It should be solved within today, but for the meantime I can temporarily remove the custom domain until it is solved.

**Comment by shomykohai** [comment]
@Chum4k3r Could you try accessing the quest system documentation from this link?
https://shomykohai.github.io/quest-system/

Edit: it seems that the issue on the is-a.dev domain is now fixed. You should be able to access the domain normally.
